In [1]:
import numpy as np 
import pandas as pd

In [2]:
df=pd.read_csv('crude-oil-price.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 469 entries, 0 to 468
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           469 non-null    object 
 1   price          469 non-null    float64
 2   percentChange  468 non-null    float64
 3   change         468 non-null    float64
dtypes: float64(3), object(1)
memory usage: 14.8+ KB


In [4]:
df['year'] = pd.DatetimeIndex(df['date']).year
df['month'] = pd.DatetimeIndex(df['date']).month
df['day'] = pd.DatetimeIndex(df['date']).day

In [5]:
df = pd.read_csv('crude-oil-price.csv',parse_dates = ['date'])

In [6]:
df.head(5)

date  price  percentChange  change
0 1983-03-30  29.27            NaN     NaN
1 1983-04-04  30.63       4.646396    1.36
2 1983-05-02  30.25      -1.240614   -0.38
3 1983-06-01  31.38       3.735537    1.13
4 1983-07-01  32.00       1.975781    0.62

In [7]:
df.drop('date', axis=1, inplace=True)

In [8]:
df.tail(5)

price  percentChange  change
464   65.85     -19.479090  -15.93
465   74.88      13.712984    9.03
466   86.49      15.504808   11.61
467   93.50       8.104983    7.01
468  107.82      15.315508   14.32

In [9]:
df.dtypes

price            float64
percentChange    float64
change           float64
dtype: object

In [10]:
df.describe()

price  percentChange      change
count  469.000000     468.000000  468.000000
mean    44.063688       0.835527    0.167842
std     28.360960      10.684412    4.951178
min     10.420000     -54.244861  -32.830000
25%     20.270000      -5.040127   -1.632500
50%     30.830000       0.956201    0.280000
75%     63.580000       6.511568    2.317500
max    140.000000      88.375796   16.650000

In [11]:
df.isnull().any()

price            False
percentChange     True
change            True
dtype: bool

In [12]:
df['percentChange'].fillna(df['percentChange'].mean(),inplace=True)
df['change'].fillna(df['change'].mean(),inplace=True)

In [13]:
df.isnull().any()

price            False
percentChange    False
change           False
dtype: bool

In [14]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
#import sklearn.grid_search
import sklearn.metrics
import sklearn.neighbors
import sklearn.decomposition
import sklearn
import sklearn.datasets
import random 
from sklearn.metrics import confusion_matrix

In [15]:
X = df.iloc[:,1:].values
print(X)
Y = df.iloc[:,0].values
print (X)
print (Y)

[[ 8.35526718e-01  1.67841880e-01]
 [ 4.64639563e+00  1.36000000e+00]
 [-1.24061378e+00 -3.80000000e-01]
 [ 3.73553719e+00  1.13000000e+00]
 [ 1.97578075e+00  6.20000000e-01]
 [-1.28125000e+00 -4.10000000e-01]
 [-3.89363723e+00 -1.23000000e+00]
 [ 3.29380764e-02  1.00000000e-02]
 [-3.75370431e+00 -1.14000000e+00]
 [ 1.26582278e+00  3.70000000e-01]
 [ 1.28378378e+00  3.80000000e-01]
 [ 1.90126751e+00  5.70000000e-01]
 [ 9.81996727e-01  3.00000000e-01]
 [-1.91247974e+00 -5.90000000e-01]
 [ 1.88367482e+00  5.70000000e-01]
 [-3.50308141e+00 -1.08000000e+00]
 [-7.22689076e+00 -2.15000000e+00]
 [ 5.90579710e+00  1.63000000e+00]
 [ 1.47109134e+00  4.30000000e-01]
 [-4.04585300e+00 -1.20000000e+00]
 [-4.04075896e+00 -1.15000000e+00]
 [-3.29549616e+00 -9.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00]
 [ 1.21166225e+00  3.20000000e-01]
 [ 5.83613917e+00  1.56000000e+00]
 [-2.33297985e+00 -6.60000000e-01]
 [ 7.60043431e-01  2.10000000e-01]
 [-3.48419540e+00 -9.70000000e-01]
 [ 9.30405657e-01  2

In [16]:
df.head()

price  percentChange    change
0  29.27       0.835527  0.167842
1  30.63       4.646396  1.360000
2  30.25      -1.240614 -0.380000
3  31.38       3.735537  1.130000
4  32.00       1.975781  0.620000

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.20,random_state=90)
fuzzy = True
num_train = len(X_train)
num_test  = len(X_test)

In [18]:
print(num_test)
print(num_train)

94
375


In [19]:
X_train

array([[ 1.60282633e+01,  4.31000000e+00],
       [ 9.22112802e+00,  3.09000000e+00],
       [ 1.78160920e+01,  9.30000000e+00],
       [ 4.06852248e+00,  7.60000000e-01],
       [-9.60307298e+00, -2.25000000e+00],
       [-9.43864878e-01, -1.90000000e-01],
       [-6.45406226e+00, -5.95000000e+00],
       [ 1.45486936e+01,  2.45000000e+00],
       [-5.31067446e-01, -1.00000000e-01],
       [ 1.47109134e+00,  4.30000000e-01],
       [ 5.26895250e+00,  3.35000000e+00],
       [ 7.38963532e+00,  3.08000000e+00],
       [-1.34209023e+01, -2.35000000e+00],
       [ 1.78537512e+01,  7.52000000e+00],
       [ 1.28378378e+00,  3.80000000e-01],
       [ 3.80952381e-01,  1.00000000e-01],
       [ 1.21166225e+00,  3.20000000e-01],
       [ 6.17512525e+00,  5.67000000e+00],
       [-2.55302435e-01, -2.60000000e-01],
       [ 1.11929922e+01,  8.05000000e+00],
       [-8.21529745e+00, -1.74000000e+00],
       [-1.06031337e+01, -4.94000000e+00],
       [ 1.06536503e+01,  7.53000000e+00],
       [-8.

In [20]:
Y_train

array([ 31.2   ,  36.6   ,  61.5   ,  19.44  ,  21.18  ,  19.94  ,
        86.24  ,  19.29  ,  18.73  ,  29.66  ,  66.93  ,  44.76  ,
        15.16  ,  49.64  ,  29.98  ,  26.35  ,  26.73  ,  97.49  ,
       101.58  ,  79.97  ,  19.44  ,  41.65  ,  78.21  ,  45.09  ,
        15.18  ,  49.2   ,  46.04  ,  15.27  ,  81.43  ,  77.    ,
        98.48  ,  43.8   ,  27.31  ,  51.12  ,  68.94  ,  27.63  ,
        29.01  ,  79.2   ,  48.52  ,  81.66  , 107.65  ,  18.75  ,
        20.42  ,  58.58  ,  51.76  ,  28.98  ,  17.94  ,  55.4872,
        21.54  ,  54.43  ,  13.34  ,  23.75  ,  26.87  ,  96.47  ,
        20.38  ,  53.72  ,  17.4   ,  51.56  ,  59.16  ,  30.85  ,
        30.55  ,  61.04  ,  19.55  ,  15.9   ,  69.96  ,  26.89  ,
        21.68  ,  92.72  ,  19.96  ,  54.07  ,  54.01  ,  29.56  ,
        30.36  ,  55.1   ,  24.15  ,  28.44  ,  27.6   ,  18.49  ,
        27.29  ,  53.79  , 102.59  ,  61.79  ,  18.83  ,  21.48  ,
        17.84  ,  19.84  ,  70.61  ,  26.29  ,  18.18  ,  65.8

In [21]:
X_test

array([[  9.87717503,   1.93      ],
       [  1.67818361,   0.34      ],
       [-11.60039435,  -3.53      ],
       [ -5.84415584,  -1.17      ],
       [ -4.08299866,  -2.44      ],
       [-17.48831887, -18.34      ],
       [ -1.81451613,  -0.36      ],
       [ -1.89655172,  -0.33      ],
       [ -1.37645108,  -0.83      ],
       [-17.86689844, -14.39      ],
       [  0.93040566,   0.25      ],
       [ 10.09406657,   2.79      ],
       [  7.1964018 ,   0.96      ],
       [ -0.98450141,  -1.01      ],
       [ -0.24290269,  -0.16      ],
       [  6.26870635,   3.77      ],
       [  9.53284672,   6.53      ],
       [  3.09601113,   2.67      ],
       [ -0.82081247,  -0.59      ],
       [  2.69151139,   2.08      ],
       [ -1.91247974,  -0.59      ],
       [  2.67527675,   0.58      ],
       [ -3.78257215,  -4.05      ],
       [-10.62937063,  -1.52      ],
       [  8.96180215,   1.83      ],
       [  5.55351232,   3.02      ],
       [ -5.81452165,  -5.95      ],
 

In [22]:
Y_test

array([ 21.47  ,  20.6   ,  26.9   ,  18.85  ,  57.32  ,  86.53  ,
        19.48  ,  17.07  ,  59.47  ,  66.15  ,  27.12  ,  30.43  ,
        14.3   , 101.58  ,  65.71  ,  63.91  ,  75.03  ,  88.91  ,
        71.29  ,  79.36  ,  30.26  ,  22.26  , 103.02  ,  12.78  ,
        22.25  ,  57.4   ,  96.38  ,  47.6   ,  25.6   ,  64.73  ,
        67.92  ,  70.68  ,  19.12  ,  33.12  ,  20.13  ,  46.86  ,
        66.63  ,  14.48  ,  18.54  , 102.7   ,  18.83  ,  15.39  ,
       113.93  ,  23.37  ,  98.83  ,  41.6   ,  45.41  ,  44.76  ,
        32.7   ,  40.22  ,  25.74  ,  30.19  ,  65.31  ,  60.42  ,
        19.89  ,  20.29  ,  15.19  ,  20.26  ,  19.8   ,  26.86  ,
        28.85  ,  40.27  ,  95.42  ,  13.26  ,  17.21  ,  52.81  ,
        67.04  ,  46.59  ,  48.32  ,  73.5992,  17.88  ,  18.05  ,
        97.49  ,  20.56  ,  29.2   ,  93.5   ,  93.46  ,  24.51  ,
        63.13  , 102.71  ,  20.96  ,  19.17  ,  45.92  ,  37.38  ,
        51.67  ,  17.56  ,  88.06  ,  56.5   ,  17.08  ,  17.6

#KNN_Algorithm

In [23]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors=1)
knn.fit(X_train,Y_train)

KNeighborsRegressor(n_neighbors=1)

In [24]:
y_pred = knn.predict(X_test)
print(y_pred)

[ 21.82    20.14    26.3     20.28    59.16    65.85    21.48    19.5
  58.58    54.43    30.85    36.16    12.05    58.58    29.11    61.79
  73.47    84.11    69.45    86.15    29.75    18.79    92.72    14.42
  25.92    64.94    88.71    46.04    22.68    60.57    74.15    74.15
  19.16    26.31    20.85    49.21    71.88    20.62    15.43    79.2
  24.59    21.2    100.36    21.37    91.97    31.04    49.72    43.45
  29.23    49.13    23.35    32.      62.91    60.14    26.87    18.39
  12.05    22.68    20.62    29.23    25.8     55.4872  98.17    18.83
  20.42    48.33    64.01    49.76    54.07    69.89    20.62    20.44
  58.58    19.61    26.25    95.98    92.72    20.19    63.58    91.82
  18.15    18.39    53.79    30.63    50.17    29.27    91.82    53.72
  18.15    18.49    53.27    19.16    20.88    30.36  ]


In [25]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(knn,X_test,y_pred, cv=10, scoring="r2").mean())

0.6514930500548475
